version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: pugs_user
      WORDPRESS_DB_PASSWORD: pugs_password
      WORDPRESS_DB_NAME: pugs_db
    volumes:
      - ./:/var/www/html/wp-content/themes/pugs
      - plugins:/var/www/html/wp-content/plugins
      - uploads:/var/www/html/wp-content/uploads

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: pugs_db
      MYSQL_USER: pugs_user
      MYSQL_PASSWORD: pugs_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  plugins:
  uploads: